#!/bin/bash

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 \"<title>\"" >&2
  exit 1
fi

filename="_posts/`date +2024-01-01-"${1}".markdown`"
filename=${filename//" "/"_"}

cat > $filename <<PTEMPLATE
---
layout: post
---

PTEMPLATE

vim ${filename}
