# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/freebsd14'

  config.vm.provider 'libvirt' do |vb|
    vb.video_type = "virtio"
    vb.memory = 2048 * 2
    vb.cpus = 4
  end

  config.vm.define "machine" do |machine|
    machine.vm.network :private_network, ip:"172.17.64.100"
  end

  config.vm.provision "shell", inline: <<-SHELL
    ifconfig | grep 172
    echo "hello"
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end
end

